export class UserLibConstants {
  static USER_LIB_REPOSITORY = 'USER_LIB_REPOSITORY';
  static POLL_LIB_REPOSITORY = 'POLL_LIB_REPOSITORY';
  static USER_POLL_LIB_REPOSITORY = 'USER_POLL_LIB_REPOSITORY';
}
